baseURL: "https://ayasismail666.github.io/"
title: "Ayas Ismail"
theme: "PaperMod"

params:
  profileMode:
    enabled: true
    title: "Your Name"
    subtitle: "HND Cloud Networking Student | IoT & Cybersecurity Explorer"
    imageUrl: "profile.png"   # put your profile pic inside /static/
    buttons:
      - name: Portfolio
        url: /portfolio/
      - name: Projects
        url: /projects/
      - name: Blog
        url: /blog/

  socialIcons:
    - name: github
      url: "https://github.com/your-username"
    - name: linkedin
      url: "https://linkedin.com/in/your-profile"
    - name: twitter
      url: "https://twitter.com/your-handle"

outputs:
  home:
    - HTML
    - RSS
    - JSON
